ENT.Type = "anim"
ENT.Base = "deployable_base"
ENT.Category = "Halo Equipment"
ENT.Author = "Sgt Flexxx"
ENT.Contact = "https://steamcommunity.com/id/sgtflexxx/"
ENT.Purpose = "To protect the user."
ENT.Instructions = "Stand under the shield for protection."
ENT.Spawnable = true
ENT.PrintName = "Bubble Shield"
ENT.ConVarName = "bubble_shield"
ENT.AutomaticFrameAdvance = true