ENT.Type = "anim"
ENT.Base = "base_gmodentity"
ENT.Category = "Halo Equipment"
ENT.Author = "Sgt Flexxx"
ENT.Contact = "https://steamcommunity.com/id/sgtflexxx/"
ENT.Purpose = "To protect the user."
ENT.Instructions = "Stand under the shield for protection."
ENT.Spawnable = false
ENT.PrintName = "Bubble Shield"