ENT.Type = "anim"
ENT.Base = "base_gmodentity"
ENT.Category = "Halo Equipment"
ENT.Author = "Sgt Flexxx"
ENT.Contact = "https://steamcommunity.com/id/sgtflexxx/"
ENT.Purpose = "To give the user Jetpack."
ENT.Instructions = "Press the activate key to activate Jetpack. Release to deactivate Jetpack."
ENT.Spawnable = true
ENT.PrintName = "Jet Pack Equipment"