ENT.Type = "anim"
ENT.Base = "base_entity"
ENT.Category = "Halo Equipment"
ENT.Author = "Sgt Flexxx"
ENT.Contact = "https://steamcommunity.com/id/sgtflexxx/"
ENT.Purpose = "To give the user a Deployable Cover."
ENT.Instructions = "Press the activate key to deploy a Deployable Cover."
ENT.Spawnable = true
ENT.PrintName = "Deployable Cover Equipment"