ENT.Type = "anim"
ENT.Base = "obj_ff_equipment_base"
ENT.Category = "Halo Equipment"
ENT.Author = "Sgt Flexxx"
ENT.Contact = "https://steamcommunity.com/id/sgtflexxx/"
ENT.Purpose = "To give the user Sprint."
ENT.Instructions = "Press the activate key to Sprint. Release the activate key to deactivate Sprint."
ENT.Spawnable = true
ENT.PrintName = "Sprint Equipment"
ENT.ConVarName = "sprint"
ENT.IconMat = Material( "icons/sprint.vmt" )
