ENT.Type = "anim"
ENT.Base = "obj_ff_equipment_base"
ENT.Category = "Halo Equipment"
ENT.Author = "Sgt Flexxx"
ENT.Contact = "https://steamcommunity.com/id/sgtflexxx/"
ENT.Purpose = "To give the user a Repulsor."
ENT.Instructions = "Press the activate key to repulse physics objects."
ENT.Spawnable = true
ENT.PrintName = "Repulsor Equipment"
ENT.ConVarName = "repulsor"
ENT.IconMat = Material( "icons/repulsor.vmt" )