ENT.Type = "anim"
ENT.Base = "base_gmodentity"
ENT.Category = "Halo Equipment"
ENT.Author = "Sgt Flexxx"
ENT.Contact = "https://steamcommunity.com/id/sgtflexxx/"
ENT.Purpose = "To regenerate health and shields."
ENT.Instructions = "Use on allies to replenish health and shields."
ENT.Spawnable = true
ENT.PrintName = "Regenerator"