ENT.Type = "anim"
ENT.Base = "obj_ff_equipment_base"
ENT.Category = "Halo Equipment"
ENT.Author = "Sgt Flexxx"
ENT.Contact = "https://steamcommunity.com/id/sgtflexxx/"
ENT.Purpose = "To give the user Evade."
ENT.Instructions = "Press the activate key to Evade."
ENT.Spawnable = true
ENT.PrintName = "Evade Equipment"
ENT.ConVarName = "evade"
ENT.IconMat = Material( "icons/evade.vmt" )
