ENT.Type = "anim"
ENT.Base = "base_gmodentity"
ENT.Category = "Halo Equipment"
ENT.Author = "Sgt Flexxx"
ENT.Contact = "https://steamcommunity.com/id/sgtflexxx/"
ENT.Purpose = "To give the user a Threat Sensor."
ENT.Instructions = "Press the activate key to send out a Threat Sensor."
ENT.Spawnable = true
ENT.PrintName = "Threat Sensor Equipment"