ENT.Type = "anim"
ENT.Base = "obj_ff_equipment_base"
ENT.Category = "Halo Equipment"
ENT.Author = "Sgt Flexxx"
ENT.Contact = "https://steamcommunity.com/id/sgtflexxx/"
ENT.Purpose = "To give the user a Grapple Shot."
ENT.Instructions = "Press the activate key to send out a Grapple Shot."
ENT.Spawnable = true
ENT.PrintName = "Grapple Shot Equipment"
ENT.ConVarName = "grapple_shot"
ENT.IconMat = Material( "icons/grapple_shot.vmt" )