ENT.Type = "anim"
ENT.Base = "obj_ff_equipment_base"
ENT.Category = "Halo Equipment"
ENT.Author = "Sgt Flexxx"
ENT.Contact = "https://steamcommunity.com/id/sgtflexxx/"
ENT.Purpose = "To give the user Invincibility."
ENT.Instructions = "Press the activate key to be temporarily invincible."
ENT.Spawnable = true
ENT.PrintName = "Invincibility Equipment"