ENT.Type = "anim"
ENT.Base = "deployable_base"
ENT.Category = "Halo Equipment"
ENT.Author = "Sgt Flexxx"
ENT.Contact = "https://steamcommunity.com/id/sgtflexxx/"
ENT.Purpose = "To displace entities."
ENT.Instructions = "Use to displace entities."
ENT.Spawnable = true
ENT.PrintName = "Portable Gravity Lift"
ENT.AutomaticFrameAdvance = true
ENT.ConVarName = "grav_lift"