ENT.Type = "anim"
ENT.Base = "base_gmodentity"
ENT.Category = "Halo Equipment"
ENT.Author = "Sgt Flexxx"
ENT.Contact = "https://steamcommunity.com/id/sgtflexxx/"
ENT.Purpose = "To blind foes."
ENT.Instructions = "Use on enemies to jam radar systems."
ENT.Spawnable = true
ENT.PrintName = "Radar Jammer"