ENT.Type = "anim"
ENT.Base = "obj_ff_equipment_base"
ENT.Category = "Halo Equipment"
ENT.Author = "Sgt Flexxx"
ENT.Contact = "https://steamcommunity.com/id/sgtflexxx/"
ENT.Purpose = "To give the user Hologram."
ENT.Instructions = "Press the activate key to send out a Hologram of the user to the pointed-at location."
ENT.Spawnable = true
ENT.PrintName = "Hologram Equipment"
ENT.ConVarName = "hologram"
ENT.IconMat = Material( "icons/hologram" )